### ISSUE TITLE
Active link of the main nav

### ISSUE THREAD

**Issue by Speirs21** [StartBootstrap/startbootstrap-agency#113]
On firefox and Edge (not on Chrome) whe we click on a link in main nav, the active link is not set properly.
![screenshot-26106d10-efbe-48df-ae3e-163a71f3cf4c-2017-08-29-12-08-24](https://user-images.githubusercontent.com/807256/29815979-caced11c-8cb2-11e7-8965-a27f6302aa0b.png)

**Comment by tasoskakour** [comment]
I agree, I face the same problem on firefox.

**Comment by xsaroz** [comment]
making offset value of scrollspy greater than 54 solved this problem for me

**Comment by Makgora** [comment]
Yeah you have to change in the agency.min.js file the value of : 

.scrollspy({target:"#mainNav",offset:54}); by .scrollspy({target:"#mainNav",offset:100});
