### ISSUE TITLE
Instructions for the contact form

### ISSUE THREAD

**Issue by ghost** [StartBootstrap/startbootstrap-agency#115]
This is an amazing theme. Thanks a lot for building it! I tried getting the contact form to work, but I couldn't. I keep getting this message: "Sorry mike, it seems that my mail server is not responding. Please try again later!" Can you provide us with instructions on how to make it work? Thanks a lot!

**Comment by MessmerSeverin** [comment]
you need to set up your own mail server and change password and mail server adress etc

**Comment by ghost** [comment]
thanks
