### ISSUE TITLE
Button and Navlink remain "focused" after being released

### ISSUE THREAD

**Issue by ionescu77** [StartBootstrap/startbootstrap-agency#12]
Hi,

while implementing the theme I noticed some inconsistency. For example:
- navigate to the [Agency Live Demo](http://ironsummitmedia.github.io/startbootstrap-agency/)
- in the top navbar click a button (team)
- after landing in the coresponding webpage section scroll up/down the page
- the original button (team) remains active even after leaving the coresponding section

I have found a js workaround but I am not sure how can it uploaded.

![screen shot 2015-02-21 at 01 46 32](https://cloud.githubusercontent.com/assets/8016748/6311445/888d2974-b96b-11e4-881e-45e928c2ee94.png)

PS Behaviour observed in Chrome 40.0.2214.111 on Mac OS X 10.9.5 mavericks

**Comment by ionescu77** [comment]
Workaround (see [Stackoverflow ID 23443579](http://stackoverflow.com/questions/23443579) ):
- open js/agency.js
- add the following

``` javascript
$(".btn-xl").mouseup(function(){
    $(this).blur();
})

$(".page-scroll").mouseup(function(){
    $(this).blur();
})
```
- reload

**Comment by abaldwin99** [comment]
Thanks for the workaround code snippet.  Worked great for me.

Shouldn't this be opened in a pull request?  I'm not sure why you'd want it any other way?

**Comment by ionescu77** [comment]
Hi, I am a beginner to GitHub collaboration :-)
I can try to make a push/pull request.
(I am doing an online seminar on git and github)

As to your question:
- I guess this issue is a "dinosaur" from multipage websites
- multi-page: you want the button to stay "pressed"
- one-page: you do not want this behaviour, because user might scroll freely to another section

**Comment by abaldwin99** [comment]
No worries on the pull request - I went ahead and put it in.  

Can you please reopen this issue?  It should stay open until @davidtmiller gets a chance to review.

**Comment by ionescu77** [comment]
Ok, thank your for your help.

**Comment by aadi7568** [comment]
Hello, I am loving the agency theme and have changed it into a multi page theme. But the problem I face is that the navigation bar doesnt work for any pages other than the home page in mobile devices. Can you please help me with this ?

**Comment by ionescu77** [comment]
For clarity, please submit a new issue. As the original one was fixed.

Thank you
