### ISSUE TITLE
Content not resized to full width on mobile in landscape mode

### ISSUE THREAD

**Issue by yurisudiev** [StartBootstrap/startbootstrap-agency#124]
On my moto x play content is not resizing to full screen when in landscape mode. screenshot : 
![screenshot_20171213-001321](https://user-images.githubusercontent.com/34027627/33909160-b597b8ea-df9b-11e7-9942-ce4a3306f3c0.png)

**Comment by guiyllw** [comment]
On my zenfone 3 I have the same problem. Apparently it happens at resolutions smaller than 353 in width.

Screenshot from chrome dev tools.

![image](https://user-images.githubusercontent.com/17480702/33919204-83fb8156-df9e-11e7-97f8-0286f8a16f87.png)

**Comment by fairuztahir** [comment]
try to replace this code in your index.html file

`<meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>`

**Comment by BaamAadmi** [comment]
@fairuztahir Thanks for the above fix. Fits perfectly after adding this meta! Cheers.
