### ISSUE TITLE
Sections should not define styles without specifier

### ISSUE THREAD

**Issue by sebastienros** [StartBootstrap/startbootstrap-agency#133]
Currently there are rules that apply to `<section>` without any constraint, which will impact the usage of the tag anywhere else.

I would suggest to apply these styles by applying them directly when `id="services"` and other sections are used.

**Comment by AlexMachin1997** [comment]
not need for this as there is one page so theres no need to do this. However, if you were to add another page then yeah that would be the best approach.

**Comment by davidtmiller** [comment]
Used as-is it isn't a problem, but I get your point. I'll modify this in the next build I do and create a class like `.page-section` or something to apply to each section with those specific styles added so the `<section>` tag can be used elsewhere without interfering with other styles.

**Comment by davidtmiller** [comment]
Fixed in 1b8c45a464dddb120df886698cb6a8bacf18388a
