### ISSUE TITLE
Issue using npm/gulp

### ISSUE THREAD

**Issue by dave-pitman** [StartBootstrap/startbootstrap-agency#134]
Giving npm a try for the first time.  Following the readme instructions for advanced use,

1. I installed nvm for windows  (https://github.com/coreybutler/nvm-windows)
2. I installed node.js latest version ( 9.8.0 64)
3. I cd to the project directory and run `npm install ` which installs 'nodes_modules' folder and content.
4. run `gulp dev` returns: 'gulp' is not recognized as an internal or external command,
operable program or batch file.'

I don't know if it is a node.js version problem or?  But following the readme for advanced use breaks down for me.

Thank you.

**Comment by AlexMachin1997** [comment]
Try install gulp seperately

**Comment by dave-pitman** [comment]
Thanks @AlexMachin1997 .  I did not know it was another toolkit that needed installed.  I installed gulp by running `npm install gulp-cli -g`

Now when I run `gulp dev `the project is loaded in the browser.  However, I must say I am still at a loss to some extent.  For example, Do I make edits in agency.css and then minify via gulp and the command line?  I am at a level that I can follow instructions, but can't really make it up on my own.  I guess I better stick to basics.

Thanks again!

**Comment by AlexMachin1997** [comment]
Hey dave, i would set it. You can either edit the scss or if your uncomfortable then you can just change the css. When changes are made if gulp detects a change it should rerun a task and then reload the browser.

If the issue is resolved i would close the issue, os its no longer an open issue.

**Comment by dave-pitman** [comment]
Thanks Alex!
