### ISSUE TITLE
"it seems that my mail server is not responding..."

### ISSUE THREAD

**Issue by hlindwin** [StartBootstrap/startbootstrap-agency#136]
Hi, How do I fix this issue? (I click "Send Message" and get "... it seems that my mail server is not responding. Please try again later!"

I uploaded the files to github and am running github pages.

Best,

Harry

**Comment by FireEmerald** [comment]
GitHub pages **do not support** sending of mails. See https://stackoverflow.com/a/24348250 for further information.

**Comment by hlindwin** [comment]
Thank you!  

What is an alternative host where this works?
I tried uploading to heroku and got an error:  "verbose stack Error: missing script: start"

What is a good host for this? How could I get this working on heroku? 

Thanks for your time!

**Comment by davidtmiller** [comment]
The best way to get around this would be to hook your form up to fromspree, it's a great way to get around the GitHub pages not supporting mail sending.

**Comment by lslamp** [comment]
I know that this ticket is closed but I ran into the same issue as mentioned above and my solution was as follows.
Make sure that you have phpmailer installed under the vendor directory.
below is my contact_me.php

//<?php
//        include_once('../vendor/phpmailer/phpmailer/src/PHPMailer.php');
//        include_once('../vendor/phpmailer/phpmailer/src/SMTP.php');
//        include_once('../vendor/phpmailer/phpmailer/src/Exception.php');

 //       $mail = new PHPMailer\PHPMailer\PHPMailer();
 //       $mail->isSMTP();
 //       $mail->SMTPAuth = true;
 //       $mail->SetFrom('noreply@{domain}.com','User');

// Check for empty fields
//if(empty($_POST['name'])      ||
//   empty($_POST['email'])     ||
//   empty($_POST['phone'])     |
//   empty($_POST['message'])   ||
//   !filter_var($_POST['email'],FILTER_VALIDATE_EMAIL))
//   {
//   echo "No arguments Provided!";
//   return false;
//   }

// Create the email and send the message
//        $host = "mail.{domain}.com";
//        $port = "587";/
//        $username = "noreply@{domain}.com";
//        $password = "{password}";

 //       $to = 'name@{domain}.com'; // Add your email address inbetween the '' replacing yourname@yourdomain.com - This is where the form will send a message to.
//        $name = strip_tags(htmlspecialchars($_POST['name']));
//        $email_address = strip_tags(htmlspecialchars($_POST['email']));
//        $phone = strip_tags(htmlspecialchars($_POST['phone']));
//       $message = strip_tags(htmlspecialchars($_POST['message']));
//        $email_subject = "Website Contact Form from:  $name";
//        $email_body = "You have received a new message from your website contact form.\n\n"."Here are the details:\n\nName: $name\n\nEmail: $email_address\n\nPhone: $phone\n\nMessage:\n$message";
//        $headers = "From: noreply@{domain}.com\n"; // This is the email address the generated message will be from. We recommend using something like noreply@yourdomain.com.
//        mail($to,$email_subject,$email_body,$headers,'-fnoreply@{domain}.com');
//        return true;

//?>

This forces the mail to be sent using the SMTP server mentioned above and it works.

Lawrence

**Comment by graphxart** [comment]
@lslamp I've did configured and uploaded the form well done and cannot solve the **"Sorry, it seems that my mail server is not responding. Please try again later!"** my hosting server sends forms fine. do you have any suggestions in order to solve it ?? see screenshot: https://prnt.sc/zvw5br
