### ISSUE TITLE
Not able to locate the vendor/scss folder. 

### ISSUE THREAD

**Issue by donwebsolutions** [StartBootstrap/startbootstrap-agency#140]
The theme is referencing a vendor/scss folder for a lot of it's styles. But not able to locate said folder as it is not there.
I am trying to integrate your theme to a laravel project. But unable to do so completely without knowing how to get the vendor/scss folder.

**Comment by vigneshprasad** [comment]
Had the same issue just run `npm rebuild node-sass` and then try if it works. That fixed it for me.

**Comment by davidtmiller** [comment]
Thanks @vigneshprasad - try this @donwebsolutions
