### ISSUE TITLE
contatct-form - more than one recipient

### ISSUE THREAD

**Issue by wini2** [StartBootstrap/startbootstrap-agency#141]
hello,

thanks for that nice and clean template.

i have some trouble with the mailform you might can resolve easily.

1. is it possible to send the contact-form to more than on recipient. i tried 
$to = 'no1@mydomain.de', 'no2@mydomain.de'; 
and 
$to = 'no1@mydomain.de no2@mydomain.de'; 
and 
$to = 'no1@mydomain.de',
$to = 'no2@mydomain.de'; 

2. how do i set a cc or bcc?

3. can i set charset somewhere?

4. is it possible to automaticaly send an mail to the registered address (so the visitor gets a copy of his mail)?
 
thanks for your help
wini2

**Comment by FireEmerald** [comment]
Search in Google for "PHP send mail cc bcc" and you will find code snipplets which do what you search for.

You will at least require a base understanding of PHP.

**Comment by davidtmiller** [comment]
I may be replacing the whole form at some point, or doing away with the scripts all together and just having the form fields and leave it to the user to add their own functionality since preferences change so much from user to user.

**Comment by davidtmiller** [comment]
Closing this since we are moving to our new SB Forms solution and no longer supporting the PHP form.
