### ISSUE TITLE
Replace jqBootstrapValidation

### ISSUE THREAD

**Issue by sebastienros** [StartBootstrap/startbootstrap-agency#142]
It's a very nice library, but the email pattern is outdated. It's only accepting domain extensions less than 3 chars, some the new domain names will never work.

See https://github.com/ReactiveRaven/jqBootstrapValidation/issues/185

The project is not taking PRs for years so it can't be fixed.

**Comment by davidtmiller** [comment]
I'm with you on this. At some point I am going to need to update the contact form quite a bit, or just do away with the working form all-together and let folks manually set up their contact forms. It was a feature that I really wanted to have, but it's been a LOT of trouble keeping it working throughout the years, and when dependencies start getting outdated it gets a bit daunting to keep updating.

I'll think about what to do with the form, thanks for this information.

**Comment by davidtmiller** [comment]
Closing this since we are moving to our new SB Forms contact forms (https://startbootstrap.com/solution/contact-forms)
