### ISSUE TITLE
not receiving e-mails from form

### ISSUE THREAD

**Issue by dbuttigieg** [StartBootstrap/startbootstrap-agency#144]
I've modified the theme a little such that I added 4 new forms (as html pages) to the website I'm working on. For some reason, I receive e-mails from the contact form which was in the theme, but not from the other 4. 

By any chance, is there anything I need to modify from the bootstrap settings it came with? I am new to frontend, and I can't really seem to find a solution for my problem. Thanks

**Comment by dbuttigieg** [comment]
I solved this issue by removing the following code in the php file: 
```
// Check for empty fields
if(empty($_POST['name'])      ||
   empty($_POST['email'])     ||
   empty($_POST['phone'])     ||
   empty($_POST['message'])   ||
   !filter_var($_POST['email'],FILTER_VALIDATE_EMAIL))
   {
   echo "No arguments Provided!";
   return false;
   }
```

**Comment by FireEmerald** [comment]
You just removed the whole server-side validation, really bad idea :-1:

**Comment by AlexMachin1997** [comment]
Not really, validation should be done on the client side as much as possible. Save the server side for processing requests like sending the email.
