### ISSUE TITLE
Standalone link of portfolio item?

### ISSUE THREAD

**Issue by boldijar** [StartBootstrap/startbootstrap-agency#145]
Hello, I'm not the best at web development, but some clues can help me do it on myself, and I just want to have a standalone link of a portfolio item, to be able to reference an exact project by url, currently just copying the url
https://blackrockdigital.github.io/startbootstrap-agency/#portfolioModal1
Won't do anything..will open the whole page, and not the portfolio modal also, do you have any idea how can I achieve this?

Thanks!

**Comment by davidtmiller** [comment]
You would just need to replace the link target with a separate HTML page. So something like `<a href="my-page.html">`
