### ISSUE TITLE
Contact Form - GDPR Consent Checkbox

### ISSUE THREAD

**Issue by alexhooley** [StartBootstrap/startbootstrap-agency#146]
Any plans for a GDPR consent checkbox like [this](https://wpforms.com/wp-content/uploads/2018/05/GDPR-Agreement-field-in-WPForms.png) with jQuery validation for the contact form?

**Comment by davidtmiller** [comment]
I'll get something like this added in the next build, thanks!

**Comment by PSX86** [comment]
Interested !

**Comment by coldcrewking** [comment]
> I'll get something like this added in the next build, thanks!

Hi, I'm having issues with where to paste %PUBLIC_URL%/ in the HTML for link tags and script tags for Mac. The classes that I watched are using windows, so there is a folder called vendor, but I did not see that on my mac. Please help.

**Comment by davidtmiller** [comment]
With the new forms service that is being used to run the contact form this is possible to add in. To get the proper markup for you, you can use our form builder here: https://startbootstrap.com/sb-form-builder and add a checkbox.
