### ISSUE TITLE
Droid Serif alternative? (GDPR)

### ISSUE THREAD

**Issue by MKahmen** [StartBootstrap/startbootstrap-agency#152]
Hi there,

here in Germany some companies are getting into trouble for loading fonts via Google server.
 
Via Google Webfont Helper I was able to download all fonts but "Droid Serif". [Google Fonts search for Droid Serif](https://fonts.google.com/?query=droid+serif) leads me to [this website](https://www.fonts.com/font/ascender/droid-serif?QueryFontType=Web&src=GoogleWebFonts) where Droid Serif is 89€!

What is the current license status for "Droid Serif" and does anyone know where I can get the font in WOFF(2) format?

Cheers and thanks for the great template!

**Comment by MKahmen** [comment]
Found the WOFF here:
https://www.fontsquirrel.com/fonts/droid-serif

Please consider shipping the webfonts in the next update.

**Comment by davidtmiller** [comment]
Interesting, is this problem still going on?

**Comment by MKahmen** [comment]
@davidtmiller yes it is.

**Comment by davidtmiller** [comment]
I am finally addressing this. I have removed Droid Serif from the fonts and moved to Roboto Slab for the subheadings fonts. Stylistically it's only slightly different, and this is also going to cut down on the load times for all of the fonts. Thanks for bringing this up and sorry it's taken so long to address!
