### ISSUE TITLE
multiple pictures in portfolio

### ISSUE THREAD

**Issue by creisey** [StartBootstrap/startbootstrap-agency#160]
hi there

im really happy with your work and it feels really seamless.

there is only one thing i'm missing.

my work is mostly 3d so i need to show a few pictues for a project. would it be possible to show more pictues than just one.

i've checked the posts description here:
https://jekyllrb.com/docs/posts/

i've i add 

![My helpful screenshot](/assets/screenshot.jpg)

i should be able to add more pictures, right...

thanks for a tipp

**Comment by davidtmiller** [comment]
You can create a carousel in place of the image within the modal window that appears after a portfolio item is clicked on.
