### ISSUE TITLE
html file away from template's root directory

### ISSUE THREAD

**Issue by biloti** [StartBootstrap/startbootstrap-agency#161]
Hi. I wonder what is the problem with placing file in subdirectories when using Agency template. I've been tring to create some pages within a subdirectories structure, but whenever a file is away from the template's root directory, fonts doesn't work anymore. Of course, I've made the adjusts in the paths explicit specified in the html file. Any clue what I'm missing?
Thanks!

**Comment by davidtmiller** [comment]
The file paths to the CSS and JS files need to updated if you are going to create HTML files within subdirectories. For example, `<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">` would need to change to `<link href="../vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">`
