### ISSUE TITLE
Error while creating new page with index page 

### ISSUE THREAD

**Issue by yashfale** [StartBootstrap/startbootstrap-agency#174]
I am trying to create new page with index page , so in this case i want only main menu bar and footer , but when i tried to to remove the` <header class="masthead"> `tag , menu background black color vanish , Question is how to get only menu bar in new page  

**For more detail :** 
https://stackoverflow.com/questions/55088738/fails-to-get-only-menu-bar-in-a-new-page-from-the-agency-bootstrap-theme

**Comment by davidtmiller** [comment]
The menu bar starts in a transparent background state and then changes to a darkened background when the page is scrolled. If the masthead is removed, then the navigation is still there, just the background is transparent and the lettering is white.

What you would need to do is change the base CSS of the navbar, or add the `.navbar-shrink` class to the navbar by default.
