### ISSUE TITLE
Error sending email from Contact Us

### ISSUE THREAD

**Issue by RamkiranRaghuraman-MachB** [StartBootstrap/startbootstrap-agency#182]
The contact us - send email throws this error, while trying to fetch the contact_me.php 

Chrome:
Failed to load resource: the server responded with a status of 405 (Not Allowed)

Microsoft Edge:
 HTTP405: BAD METHOD - The HTTP verb used is not supported.
(XHR)POST - https://www.edugence.com/mail/contact_me.php

**Comment by davidtmiller** [comment]
https://stackoverflow.com/questions/24644436/php-mail-function-doesnt-complete-sending-of-e-mail# Try the suggestions here!
