### ISSUE TITLE
Blog Pages

### ISSUE THREAD

**Issue by binaryfog** [StartBootstrap/startbootstrap-agency#202]
There are any plans to add blog pages ? For example, a section of last 5 most recent blog posts in the home page, an additional page for all blog posts and blog post detail page?

**Comment by davidtmiller** [comment]
At the moment no, but it's something we could look into for a future version.

**Comment by point000** [comment]
how can i change the css code ??? when im updatind it in styles.css it's not working

**Comment by binaryfog** [comment]
> how can i change the css code ??? when im updatind it in styles.css it's not working

You need to change the scss code , not the css code. css is regenerated an every build from the scss.

**Comment by davidtmiller** [comment]
I don't think we are going to move into multi-page layouts for this theme at the moment, so I am closing this for now.
