### ISSUE TITLE
Agency theme-nav bar problem on mobile devices

### ISSUE THREAD

**Issue by aadi7568** [StartBootstrap/startbootstrap-agency#21]
I am using the agency theme as a multi page theme but the problem I face is that when I switch to any page on my website other than the home page the navigation bar doesnt work. I dont know whats wrong. Can somebody help ?

**Comment by abaldwin99** [comment]
This is likely not an issue with the agency code but is an issue with the changes you made when turning it into a multi-page site.  You probably need to check that your hrefs are pointing to the correct page.  You can test this by changing...

```
<a class="page-scroll" href="#portfolio">Portfolio</a>
```

to...

```
<a href="/about">Portfolio</a>
```

If you upload your fork to github or provide the url it's hosted at I'll take a quick glance at it.  Also what do you mean by not working?  Clicking on the links causes no action whatsoever?

**Comment by aadi7568** [comment]
Thanks for replying back. By not working I mean that the navigation bar on mobile devices doesnt work except for the home page. the site url is www.platzo.com ...the navigation bar in about page and the contact page doesnt work on mobile devices.

**Comment by abaldwin99** [comment]
Well for one you're missing a closing div in your navbar.  Hopefully that gets you fixed up.

Also - Not the source of your problem but links to pages on the same domain can be cleaned up...

```
href="http://platzo.com/contact.html"
```

should be...

```
href="/contact.html"
```

**Comment by aadi7568** [comment]
Thanks for replying. I did put the closing div in the navbar. but the problem still seems to exist. I would like you to please go through the code and let us know why the navigation bar doesn't work on mobile devices. 
thanks

**Comment by abaldwin99** [comment]
Pound signs (#) and dots (.) are used for referencing another HTML/DOM element.  However they are NOT used in class or id attribute values.

```
<div class="collapse navbar-collapse" id="#myNavbar">
```

should be...

```
<div class="collapse navbar-collapse" id="myNavbar">
```

The link from your navbar toggle div to your navbar collapse div is broken because of this.

**Comment by aadi7568** [comment]
Thanks a lot. I was stuck with this problem since like a week. Thanks. I was wondering can you please check out our about page and help me with the social media buttons. they just don't show up, in the amazing team section. 
thanks.

**Comment by abaldwin99** [comment]
You're welcome.  I can help you debug your site but not for free.  If you want to discuss please get in touch using my profile's public email so we don't clog up everyone's inbox.  Alternatively you can pursue answers on stackoverflow but you'll need to work on getting minimal examples. http://stackoverflow.com/help/mcve

Please close this issue so others know it is not am open problem with this repo.
