### ISSUE TITLE
Contact us not emailing

### ISSUE THREAD

**Issue by mega-mattice** [StartBootstrap/startbootstrap-agency#214]
I updated my email address in the .php file, but am not receiving the email form in my inbox.

I checked my php server which is running v7. Any suggestions?

**Comment by ghost** [comment]
Hi,
Is the php Contact Us Form compatible with PHP version 7?
I've been happily using the Contact Us form for a few years using PHP 5 - but now it's stopped working too.
I suspect I have a similar issue as Boximity-Dev. 
I've not checked any issues with my host yet, but they have also updated their servers to run PHP Version 7.2.20. 
I'm grateful for using your great template, but any sugguestions?

**Comment by FireEmerald** [comment]
The contact us form only uses the [`mail()`](https://www.php.net/manual/en/function.mail.php) function of PHP, which still exists in PHP 7. So it's definitely an issue on your server. Take a look at [this](https://stackoverflow.com/a/40753804/4300087) topic for further ideas how you may solve your problem.

**Comment by mega-mattice** [comment]
I have resolved this issue (at least for myself). I was forwarding it to an address that was not recognized by my server (siteground). When I changed it to an address hosted by my server, the email was sent. See attached:

https://www.siteground.com/kb/do-i-need-a-valid-email-account-to-use-sendmail/
