### ISSUE TITLE
Changes to agency(.min).css reverting when using npm start.

### ISSUE THREAD

**Issue by TaylorZowtuk** [StartBootstrap/startbootstrap-agency#216]
I made a couple of additions to the agency.css which I manually minified and added to the agency.min.css (though im now realizing that gulp should handle that for me but thats beside the point...). I was able to use npm start without any issues with these additions for a while but recently performing npm start replaces my agency.css and agency.min.css with the template css (ie. without my additions). I'm wondering why this is? Is there a different way im supposed to make modifications to the css? The change in behaviour came after I did a push to my repository and recloned my repo locally. 

It seems like im supposed to make my own css and load it later overwriting anything I want it to instead of modifying the agency.css directly is this correct?

**Comment by TaylorZowtuk** [comment]
As per #134, I decided to edit the scss files where needed. This resolves the issues of npm start replacing my css modifications and properly minifies my changes also.

I still am curious why npm start worked for some time and then decided to start forcing the template css if anyone can answer that?

**Comment by calebfergie** [comment]
@TaylorZowtuk I'm experiencing the same issue. Would prefer not to edit anything but the single `agency.css` file...

**Comment by davidtmiller** [comment]
When the build scripts are run, it builds the CSS from the SCSS. If you make changes to the minified CSS file, and then run the build, they will just get overwritten by the new build.

The best way to build using the build environment is to modify the SCSS, then run the build, and the changes will be seen.
