### ISSUE TITLE
Background content scrolls when trying to scroll content in modal

### ISSUE THREAD

**Issue by 5ero** [StartBootstrap/startbootstrap-agency#218]
When clicking on a project in the portfolio section, a modal opens and the content is scrollable.
However when scrolling content in the modal, the modal scroll stops and the content underneath modal scrolls.

This behaviour is noted on iPhone X in Safari

**Comment by davidtmiller** [comment]
I think this is just browser behavior interfering with Bootstrap rather than the theme styling.
