### ISSUE TITLE
Re-Captcha

### ISSUE THREAD

**Issue by bruckbmrj** [StartBootstrap/startbootstrap-agency#221]
Thanks for this beautiful and nice template!
I don't know if this is an issue, maybe more a question, i try to use google re-captcha in contact form, but without success, can you help to solve this?

**Comment by FireEmerald** [comment]
Your questions has nothing to do with the `startbootstrap-agency` template itself.

If you are not able to implement this feature on your own, search on google for someone who implement it for you - but not here.
