### ISSUE TITLE
SMTP Authentication issues

### ISSUE THREAD

**Issue by lslamp** [StartBootstrap/startbootstrap-agency#223]
I am having an issue with sending emails generated by the contact form. I am running my web site on my own server and my email hosting service is being run by an ISP in the UK.
I am having a lot of issues where I cannot fill in the form because the mail is not being sent.
I am running multiple domains on the same server and when the mails are generated, postfix is being used to send the emails. One of my sites is using the bootstrap-agency template.
I am not a developer in any way, but I have found a page on smtpjs, where javascript can be used to authenticate on the remote smtp server because the error I am seeing is that I cannot get the authentication sorted.
Is there a way in bootstrap to configure authentcation to the SMTP server for the forms that need to be sent?

below is an extract from my mail.log file.
Nov 13 23:34:34 dunnsland postfix/pickup[12066]: 3776F9C35: uid=33 from=<www-data>
Nov 13 23:34:34 dunnsland postfix/cleanup[12073]: 3776F9C35: message-id=<20191113233434.3776F9C35@hockeysticks4clubs.com>
Nov 13 23:34:34 dunnsland postfix/qmgr[12067]: 3776F9C35: from=<info@hockeysticks4clubs.com>, size=581, nrcpt=1 (queue active)
Nov 13 23:34:34 dunnsland postfix/smtp[12076]: 3776F9C35: to=<info@hockeysticks4clubs.com>, relay=mail.hockeysticks4clubs.com[89.145.69.246]:587, delay=0.27, delays=0.02/0/0.22/0.03, dsn=5.0.0, status=bounced (host mail.hockeysticks4clubs.com[89.145.69.246] said: 550 SMTP AUTH is required for message submission on port 587 (in reply to RCPT TO command))
Nov 13 23:34:34 dunnsland postfix/cleanup[12073]: 761A09C37: message-id=<20191113233434.761A09C37@hockeysticks4clubs.com>
Nov 13 23:34:34 dunnsland postfix/bounce[12078]: 3776F9C35: sender non-delivery notification: 761A09C37
Nov 13 23:34:34 dunnsland postfix/qmgr[12067]: 761A09C37: from=<>, size=2669, nrcpt=1 (queue active)
Nov 13 23:34:34 dunnsland postfix/qmgr[12067]: 3776F9C35: removed
Nov 13 23:34:34 dunnsland postfix/smtp[12076]: 761A09C37: to=<info@hockeysticks4clubs.com>, relay=mail.hockeysticks4clubs.com[89.145.69.246]:587, delay=0.13, delays=0.01/0/0.11/0.01, dsn=5.0.0, status=bounced (host mail.hockeysticks4clubs.com[89.145.69.246] said: 550 SMTP AUTH is required for message submission on port 587 (in reply to RCPT TO command))
Nov 13 23:34:34 dunnsland postfix/qmgr[12067]: 761A09C37: removed

Thanks in advance
Lawrence

**Comment by FireEmerald** [comment]
The mail is sent via a [PHP script](https://github.com/BlackrockDigital/startbootstrap-agency/blob/b8336230c91e37542c1b23964d1abc7897fa731a/mail/contact_me.php#L24). Bootstrap has nothing to do with this.
Google for _"smtp auth php"_ or _"postfix smtp auth"_.

Your issue is not related to this theme.

**Comment by lslamp** [comment]
Thank you
