### ISSUE TITLE
issues with sending emails - phpmailer questions

### ISSUE THREAD

**Issue by lslamp** [StartBootstrap/startbootstrap-agency#224]
I am new to this so I am not 100% sure it this is even the correct location to post my issue. Please forgive me if not and point me into the right direction and I will happily ask the question elsewhere.

When I first installed bootstrap, the contact form worked as expected. Only the form contents were being sent through postfix to my relay server. After an update, this process stopped working. 
After a few days of trying to figure things out, I turned to PHPMailer.
No matter what I tried I could not get the contact form to work. 
I eventually started working on a test php script, something that I could use PHPMailer to send, authenticate and deliver emails. I eventually managed to get this to work, but now I have to implement what I have done/found into the contact form.
That is where my development skills fall apart.
So I hope that someone can help me.

First of all, I had to update the version of PHPMailer to 6.3. When I did this there is a known issue with PHP 7.3. You cannot use composer to install the latest version of PHPMailer.  The fix is pretty simple as well. ( I can elaborate if required, please ask.)

After the installation, below is the test php script that I created to test sending emails to an SMTP server with encryption.

mail.php --> this successfully sends an email to the recipient. 
<?php 

    include_once('/usr/share/php/vendor/phpmailer/phpmailer/src/PHPMailer.php');
    include_once('/usr/share/php/vendor/phpmailer/phpmailer/src/SMTP.php');
    include_once('/usr/share/php/vendor/phpmailer/phpmailer/src/Exception.php');

    use PHPMailer\PHPMailer\PHPMailer;
    $mail = new PHPMailer();
    $mail->isSMTP();
    $mail->Host = 'mail.hockeysticks4clubs.com';
    $mail->SMTPAuth = true;
    $mail->Username = 'info@hockeysticks4clubs.com'; //paste one generated by Mailtrap
    $mail->Password = 'P4WnbcN6t1m?'; //paste one generated by Mailtrap
    $mail->SMTPSecure = 'ssl';
    $mail->Port = 465;
    $mail->setFrom('noreply@hockeysticks4clubs.com', 'HockeySticks4CLubs');
    $mail->addAddress('lawrence@e2snail.com', 'Lawrence'); 
    $mail->Subject = 'Test Email via Dunnsland SMTP using PHPMailer';
    $mail->isHTML(true);
    $mailContent = "<h1>Send HTML Email using SMTP in PHP</h1>
    <p>This is a test email I’m sending using SMTP mail server with PHPMailer.</p>";
    $mail->Body = $mailContent;
    $mail->send();

    if($mail->send()){
    echo 'Message has been sent';
     }else{
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
    }
?>

Now the issue that I have is I have no clue how to incorporate this into the bootstrap contact form logic.

Is there anyone out there that can help me merge the above script into the contact-me.php script.

When I do try some things, I keep getting the error
"Sorry Lawrence, it seems that my mail server is not responding. Please try again later!"

Thanks
Lawrence

**Comment by lslamp** [comment]
Also, I am not sure that this is the correct place to ask this question
Lawrence

**Comment by davidtmiller** [comment]
Here is a great article on StackOverflow addressing issues with the PHP mailer: https://stackoverflow.com/questions/24644436/php-mail-function-doesnt-complete-sending-of-e-mail#
