### ISSUE TITLE
Broken: Auto-Scroll (Mouse Middle-clicking)

### ISSUE THREAD

**Issue by Daraghmeh** [StartBootstrap/startbootstrap-agency#24]
When auto-scroll is used, the site will lock up the mouse and cause the site to not beable to move.

Recreate Issue: Simply go to the site demo @http://ironsummitmedia.github.io/startbootstrap-agency/ and click the middle button of on your mouse's scroll wheel.

This mouse icon will turn into this (icon demands on OS/Browser)
![autoscroll](https://cloud.githubusercontent.com/assets/4383833/7106969/b74ff52e-e121-11e4-9ec1-9635b3a9ff59.png)

**Comment by ionescu77** [comment]
Which operating system version and browser?

**Comment by Daraghmeh** [comment]
Windows 8.1 with all browsers from Chrome 43.0.2357.124 to Firefox 37.0.2 to IE. Sorry for the delay

**Comment by Daraghmeh** [comment]
Closed this Issue for it seems this an issue with browsers in general and on different sites as well.
