### ISSUE TITLE
js problem

### ISSUE THREAD

**Issue by codebdy** [StartBootstrap/startbootstrap-agency#244]
I add your theme to my editor as an demo, but info me a js error:
```
agency.min.js:7 Uncaught TypeError: Cannot read property 'top' of undefined
    at a (agency.min.js:7)
    at agency.min.js:7
    at agency.min.js:7
```
address:http://vular.cn/rxeditor/
can you help me fix it?
![image](https://user-images.githubusercontent.com/18096128/75533573-9b248700-5a4f-11ea-8921-ade80cfb9fb6.png)

by the way, the html filse is in an iFrame, and I load it by contentDocument.write() method

**Comment by davidtmiller** [comment]
If the smooth scrolling function isn't firing, then it will give this error. You can delete the function from the JS if you're not using the function, or you can add parameters to the function if you want to look for cases that the navbar isn't being used in that way. Not loading jQuery will also give this error.
