### ISSUE TITLE
[question] How to make portfolio as webpage.

### ISSUE THREAD

**Issue by ozbillwang** [StartBootstrap/startbootstrap-agency#258]
when click one of portfolio previous image, it shows a new page, such as 

https://blackrockdigital.github.io/startbootstrap-agency/#portfolioModal5

But this page can't be displayed directly if I copy and paste in browswer. 

Any way I can make the page as seperate url which I can access directly.

**Comment by davidtmiller** [comment]
You can create your own HTML page and then link to it using an href
