### ISSUE TITLE
elem is null in classie.js addClass with Visual Studio and Umbraco

### ISSUE THREAD

**Issue by Hardstyl3R** [StartBootstrap/startbootstrap-agency#26]
Hi togehther,
I use the Agency Theme for Umbraco and i develop with visual studio.

I recognize a nullpointer exception when i scroll down in the homepage so that the navbar should change like it is in your preview solution:

![agency issue -3-](https://cloud.githubusercontent.com/assets/11586476/7447865/8c11460c-f20a-11e4-8086-f5104ac3ec2e.PNG)

cbpAnimatedHeader.min.js:
![agency issue -1-](https://cloud.githubusercontent.com/assets/11586476/7447866/8c130afa-f20a-11e4-9123-90e0920db981.PNG)

classie.js:
![agency issue -2-](https://cloud.githubusercontent.com/assets/11586476/7447864/8c0ee196-f20a-11e4-8004-a01754cb8f1a.PNG)

The result of this is a navbar, that isn't changing their background:

![agency issue -4-](https://cloud.githubusercontent.com/assets/11586476/7447863/8c09e362-f20a-11e4-9bae-04b5cf60dd5e.PNG)

A jQuery Code fixed this problem, but then the "active" class in the navbar isn't working correctly:

![agency issue -6-](https://cloud.githubusercontent.com/assets/11586476/7447861/8be1d23c-f20a-11e4-9e37-a3d6549ff2d9.PNG)

Do you have a solution for this?

jQuery Code:
$(function () {
    $(window).scroll(function(){
        if ($(this).scrollTop() > 300){
            $('.navbar-default').addClass('navbar-shrink');
        }
        else{
            $('.navbar-default').removeClass('navbar-shrink');
        }
    });
});

Included .js and .css files:

![agency issue -5-](https://cloud.githubusercontent.com/assets/11586476/7447862/8c05419a-f20a-11e4-951f-9a8a7125c897.PNG)

**Comment by davidtmiller** [comment]
I'm going to dump classie.js and cbpanimatedheader.js soon in favor of just using the built in Bootstrap scrollspy stuff along with some affix stuff that is built in. Thanks for this info though!

**Comment by nonameolsson** [comment]
What's the status of this?

**Comment by davidtmiller** [comment]
Classie has been removed and the affix plugin is being used for the collapsing header now instead.
