### ISSUE TITLE
Top undefine within Agency.min.js

### ISSUE THREAD

**Issue by GeekDoom** [StartBootstrap/startbootstrap-agency#261]
![agencyerror](https://user-images.githubusercontent.com/9118535/79516610-82792c00-8011-11ea-8ff4-e9519832fb97.png)
Hello there, im using this theme for practicing react, but im getting "agency.min.js:7 Uncaught TypeError: Cannot read property 'top' of undefined" and idk why is that (without react, i can run it perfectly) can anyone helpme?

**Comment by davidtmiller** [comment]
This error will appear if the project isn't using jQuery.
