### ISSUE TITLE
Map image giving problems

### ISSUE THREAD

**Issue by Ridge-IT** [StartBootstrap/startbootstrap-agency#27]
![map image](https://cloud.githubusercontent.com/assets/8385845/7455979/13aa5fe2-f281-11e4-9dd2-a0c2c5b8cd96.JPG)
Hi, the map image keeps showing on the screen as if the column was set to: <div class= ".col-lg-10 .col-lg-offset-1"></div>. Does anyone have a solution to this problem? And client mail doesn't seem to be getting through to me.

**Comment by ionescu77** [comment]
Re Map Image:
I had no issues reported yet; please specify the context (how can this error be reproduced):
- which browser you were using
- evetually which screen (mobile/laptop/PC) and resolution.
  Re Email:
  I am not using the php script, but
- have you filled the correct details in ./mail/contact.php?
- you webhost is configured to run php scripts?
- is there a mail server on your webhost?
  Hope it helps,
  Thank you

**Comment by Ridge-IT** [comment]
I'll say yes to all, my host has php 5.3 and I'm using the latest firefox browser.

**Comment by Ridge-IT** [comment]
I managed to fix the php script that had conflict with the HTML, but still can't fix the map part.

**Comment by davidtmiller** [comment]
Not sure what's going on here, look for stray tags is all I can say as a starting point!
