### ISSUE TITLE
Where is the index.htm file?

### ISSUE THREAD

**Issue by prensmiskin** [StartBootstrap/startbootstrap-agency#278]
The index.htm file does not exist. Please add.

**Comment by AlexMachin1997** [comment]
src/pug - https://github.com/BlackrockDigital/startbootstrap-agency/blob/master/src/pug/index.pug

**Comment by davidtmiller** [comment]
Yes @AlexMachin1997 is correct. The source files use Pug, which is an HTML templating engine. If you are looking for the `index.html` file, and don't want to use the source files of this theme, simply go to the `dist` directory to see the static HTML/CSS version of the theme itself.
