### ISSUE TITLE
I converted this to a Jekyll theme!

### ISSUE THREAD

**Issue by raviriley** [StartBootstrap/startbootstrap-agency#279]
## [raviriley/agency-jekyll-theme/](https://github.com/raviriley/agency-jekyll-theme/)

I wanted to use this theme in Jekyll on GitHub Pages, so I decided to convert the newest Bootstrap code to a Jekyll theme from scratch. Then, once I started using the theme, I realized I could make some additions to make the original theme more useful, such as Google Analytics support, a functional, backend-less contact form (works on static sites + GitHub Pages), customizable styling, etc. 
Check out the details [here](https://github.com/raviriley/agency-jekyll-theme/)!

https://github.com/raviriley/agency-jekyll-theme/

Let me know if you run into any issues!

**Comment by davidtmiller** [comment]
Thanks for sharing! I will check it out.
