### ISSUE TITLE
Centering a picture

### ISSUE THREAD

**Issue by eerga** [StartBootstrap/startbootstrap-agency#283]
Dear David, 
I don't know CSS that well, so I apologize for the question in advance. In the Portfolio page, I am using only 4 pictures instead of 6 and I've tried different code combinations to center the 4th picture but nothing was successful. However, I am not sure how to center the last picture. Those are the latest modifications I performed in the index.html file:
 <div class="box">
    <img class="img-fluid" src="{% static 'assets/img/portfolio/06-thumbnail.jpg'%}" alt="" />
</div>    

And here is what I added in the .css file:
.box {
  text-align: center; /*modified*/
}

It's not working, so obviously I did something wrong.

**Comment by davidtmiller** [comment]
On the `.row` element, add the `.justify-content-center` utility class and it should center that picture for you!
