### ISSUE TITLE
npm install and npm start errors

### ISSUE THREAD

**Issue by dee0001** [StartBootstrap/startbootstrap-agency#295]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! startbootstrap-agency@6.0.2 start: `npm run build && node scripts/start.js`
npm ERR! Exit status 1

I already tried to remove node_modules folders and package-lock.json.

I cannot find the error. Thanks for your help.

**Comment by davidtmiller** [comment]
This should be resolved at this point - also try updating your version of npm.
