### ISSUE TITLE
Code is generating links to undesired content

### ISSUE THREAD

**Issue by vpxavier** [StartBootstrap/startbootstrap-agency#296]
Hello, 
I downloaded the latest version to date and uploaded to my hosting (OVH).
When I amchecking the code with developper tools and the Lighthouse analysis, I saw there was an advice to remove unused CSS.
I thought it was because I removed the portfolio sections and modals but I see that a code is generated that links to indesirable websites. The link is changing each time I run the analysis.
See here:
<a href="https://ibb.co/xDNgZFR"><img src="https://i.ibb.co/VtsC6wP/screen1.jpg" alt="screen1" border="0"></a>

and here:

<a href="https://ibb.co/sKB5v4m"><img src="https://i.ibb.co/v3tsxWw/screen2.jpg" alt="screen2" border="0"></a>

**Comment by davidtmiller** [comment]
We aren't able to replicate this issue. There could be a browser extension or something else that you have running locally on your machine that is causing this issue. If you can provide more details I can check further, but I am unable to replicate this at the moment.
