### ISSUE TITLE
SASS Support

### ISSUE THREAD

**Issue by johnvoloski** [StartBootstrap/startbootstrap-agency#30]
It would be interesting to have the option of using "sass" instead of "less".

**Comment by davidtmiller** [comment]
With Bootstrap 4 on the horizon, I'll be adding SASS and LESS support for all themes (instead of just LESS)

**Comment by elendirx** [comment]
+1

**Comment by andrewwu** [comment]
Please see PR #59 for Sass support.

**Comment by davidtmiller** [comment]
The PR was added, and I need to do a little cleanup of the SASS file due to some LESS changes but now the template will have both LESS and SASS as options for developers to use!
