### ISSUE TITLE
Send information fetched from MongoDB to front

### ISSUE THREAD

**Issue by SerasAlin** [StartBootstrap/startbootstrap-agency#302]
Hello everyone ! 
First of all I want to thank you for creating this superb template :).
I have managed to connect my MongoDB to the application ( doing this inside start.js ) and printed the content of the tables in the console.
I got stuck when trying to send this information to the front, for example, to the index.pug. Can anyone assist me in any way ? I would very much appreciate it ! Thank you.

**Comment by davidtmiller** [comment]
Hi there, unfortunately that is outside of the scope of the theme, and I don't personally have any experiencing hooking up MongoDB apps. I would try to look around on Stackoverflow to see if that can help!
