### ISSUE TITLE
Equal height of boxes

### ISSUE THREAD

**Issue by dee0001** [StartBootstrap/startbootstrap-agency#306]
I am trying to apply <div class="row row-eq-height"> on a row with three boxes/columns, but the boxes do not alight to the same height. I am not sure what I am missing? Thanks for your advice.

**Comment by davidtmiller** [comment]
Within each column, set the height of the first element to `.h-100`. For example:

```
<div class="row">

    <div class="col-lg-4">
        <div class="card h-100">
                ...
        </div>
    </div>

    <div class="col-lg-4">
        <div class="card h-100">
                ...
        </div>
    </div>

    <div class="col-lg-4">
        <div class="card h-100">
                ...
        </div>
    </div>

</div>
```

In the above example, the three cards in each column will be the same height.
