### ISSUE TITLE
Form Consent

### ISSUE THREAD

**Issue by ggonz20** [StartBootstrap/startbootstrap-agency#307]
Hi, I have been trying to use the consent form. It says message sent but I don't get nothing in my email in box. I am using php7.4 on my webhosting server.

**Comment by davidtmiller** [comment]
Hi there, the forms are being reworked using our new SB Forms solution and the PHP forms are no longer being supported. If you are trying to troubleshoot the old PHP for, take a look at this issue on Stackoverflow which will help explain things https://stackoverflow.com/questions/24644436/php-mail-function-doesnt-complete-sending-of-e-mail#

Or visit https://startbootstrap.com/solution/contact-forms (coming soon) to check out our form solution for static sites!

**Comment by ggonz20** [comment]
David,
Thanks for reaching out. I was  able to get the forms to work after a 2 weeks of tinkering with my box. Thank  you for making this website!
Sincerely,
Gerardo

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
