### ISSUE TITLE
Generate navbar-logo.svg with different text

### ISSUE THREAD

**Issue by wernerwws** [StartBootstrap/startbootstrap-agency#311]
Is there a way to generate the `src/assets/img/navbar-logo.svg` with a different text?

**Comment by davidtmiller** [comment]
The `navbar-logo.svg` file is just to demonstrate the use of an SVG within the navbar brand element. You would have to make your own SVG image. For reference, the demo image was made using the [Kaushan Script](https://fonts.google.com/specimen/Kaushan+Script) font. Hopefully this helps!
