### ISSUE TITLE
Scrolling in Modals Stopped working

### ISSUE THREAD

**Issue by tameanaka** [StartBootstrap/startbootstrap-agency#33]
When I open up one of the portfolio modals I can no longer scroll using the mouse wheel or arrows.  Page up and down work just fine.  I am using Chrome 43 and Win7 64.  IE works just fine.  When I open Dev tools in Chrome scrolling starts working instantly.

**Comment by davidtmiller** [comment]
Not sure if this is a template problem or a Bootstrap modals problem. I'll look into it though, thanks.
