### ISSUE TITLE
.navbar-brand is different in bootstrap.min.css vs bootstrap.css

### ISSUE THREAD

**Issue by cori7374** [StartBootstrap/startbootstrap-agency#36]
Hello,
I just figured out why my logo at the top-left corner of the page in the navbar was not lining up correctly.  I believe it has to do with the navbar-brand:

bootstrap.min.css version
.navbar-brand{
float:left;
height:50px;
padding:5px 5px;
font-size:18px;
line-height:20px
}

bootstrap.css version
.navbar-brand {
  float: left;
  height: 50px;
  padding: 15px 15px;
  font-size: 18px;
  line-height: 20px;
}

That little bit of padding made the difference in how my logo was aligned.
![navbar using bootstrapmin css](https://cloud.githubusercontent.com/assets/8904348/9505091/49f6a286-4c0e-11e5-8ea6-956b16cac7e7.jpg)
![navbar using bootstrap css](https://cloud.githubusercontent.com/assets/8904348/9505090/49f4ffa8-4c0e-11e5-8b82-1838e006c6bd.png)

Please forgive me if this has been resolved.  I have been staring at code for over 2 hours before I found the discrepancy. :)

**Comment by davidtmiller** [comment]
Hmm interesting, where was it at? I am relatively sure that the bootstrap.css and bootstrap.min.css files weren't tampered with in the creation of this theme.

**Comment by davidtmiller** [comment]
This should be standardized now.
