### ISSUE TITLE
Media buttons missing in   <!-- Team Section -->

### ISSUE THREAD

**Issue by chwieser** [StartBootstrap/startbootstrap-agency#46]
Thank you for the great template - saved me a lot of time. 

Could you help me figuring out what I am doing funnily? The media buttons in the Team Section shows up when running locally, but not when uploaded to the server. Servers error log shows nothing. 

![screen shot 2016-02-04 at 16 52 28](https://cloud.githubusercontent.com/assets/1791963/12818617/4a664894-cb60-11e5-82f7-726260cfee64.png)
![screen shot 2016-02-04 at 16 52 04](https://cloud.githubusercontent.com/assets/1791963/12818618/4a68cac4-cb60-11e5-9659-00041b441399.png)

Thank you for any advise,

Christian

**Comment by FireEmerald** [comment]
Check the paths of your imports. Especially for Font Awesome Icons.

```
<link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
```

**Comment by chwieser** [comment]
My mistake - had been an activated Ad-blocker. Sorry.

**Comment by davidtmiller** [comment]
Glad you figured it out!

**Comment by YannickGibson** [comment]
> My mistake - had been an activated Ad-blocker. Sorry.

Thanks, I had the same problem by mistake
