### ISSUE TITLE
Add extra individual modal-content?

### ISSUE THREAD

**Issue by haru1001** [StartBootstrap/startbootstrap-agency#47]
Sorry, might be stupid question. But I can't figure out what is the problem.
I could add more portfolio-hover to index.html but when I try to make the 7th+ modal-content, 
it stopped to work. It only shows the modal-content from 6th.
What & Where do I need to adjust?

Many thanks!

**Comment by FireEmerald** [comment]
You need a minimum understanding for HTML and CSS to fix this problem on your own, or provide an example link.

Check the `<a href="#portfolioModalX" class="portfolio-link" data-toggle="modal">` line.
The href attribute must be equal to the modal-content.

**Comment by haru1001** [comment]
@FireEmerald Oh problem fixed! just missed to change a number... Thank you...
