### ISSUE TITLE
Closing modals with esc-key doesn't work

### ISSUE THREAD

**Issue by cleptric** [StartBootstrap/startbootstrap-agency#48]
The portfolio modals can't be closed by pressing the esc key. I think the problem is that you forgot to add a div with class modal-dialog beneath the portfolio-modal div.

**Comment by davidtmiller** [comment]
I am not sure if there is a JavaScript way to make this happen, I'd be interested in finding out.

**Comment by cleptric** [comment]
was fixed in pr #62
