### ISSUE TITLE
Issue with classie.js?

### ISSUE THREAD

**Issue by avery-laird** [StartBootstrap/startbootstrap-agency#5]
I'm no js expert, so this may seem like a silly problem to be having, but I've been attempting to integrate this theme with a django backend. In the process of getting just the barebones static content to display properly, I hit one sticking point: a thrown error in classie.js, line 36, specifically: `Uncaught TypeError: Cannot read property 'classList' of null`. Obviously  the `classList` property is returning null, probably from an inability to gather the classes of the navbar, but as I said, that's a wild guess since my js chops are pretty much nonexistent. Any insight?

**Comment by avery-laird** [comment]
never mind, solved my own issue

**Comment by fourroses666** [comment]
then you can close the issue :)

**Comment by avery-laird** [comment]
my bad, forgot

**Comment by PhilippMeissner** [comment]
Hey avery-laird - I experience the very same issue. Would you mind sharing how you got rid of this problem? :)
