### ISSUE TITLE
Can't upload agency theme to wordpress: "CSS stylesheet missing"

### ISSUE THREAD

**Issue by Thermax** [StartBootstrap/startbootstrap-agency#50]
Hi Guys, your Agency theme looks great! It's exactly what I'd like to work with, but I'm having trouble uploading it to my server for wordpress. I've tried through both the wp/admin interface and through my FTP, CPanel. Can you please advise what the issue may be and how we might go about fixing it?

Cheers,
M

**Comment by davidtmiller** [comment]
Agency isn't a WordPress theme, it's just raw HTML and CSS.
