### ISSUE TITLE
Contact Form Does not Work

### ISSUE THREAD

**Issue by christopher-bobby** [StartBootstrap/startbootstrap-agency#51]
I have tried changing the email address couples of times, but it resulted the same.. I have no idea why.. Anyone experienced this before?

**Comment by kintaro1981** [comment]
same problem here
it say "Message Sent" but no massage received.

php 5.6

**Comment by kintaro1981** [comment]
in my case is postfix configuration problem, so @subtlefluids01 try to look in your server logs

**Comment by davidtmiller** [comment]
If you're trying to send mail while looking at the site locally (without a mail server) then the form may give a false positive. Otherwise it might be a permissions or security feature on your web hosts servers. You may want to troubleshoot this with your hosting provider.
