### ISSUE TITLE
"Close Portfolio" button requires two touches on mobile to close.

### ISSUE THREAD

**Issue by prabintim** [StartBootstrap/startbootstrap-agency#57]
Once the portfolio is opened on a mobile browser, the Close Portfolio button needs to be pressed twice to close.

**Comment by prabintim** [comment]
Happens when you scroll fast to the bottom.

**Comment by davidtmiller** [comment]
What mobile OS?

**Comment by prabintim** [comment]
Android -> Chrome, Default Browser.

When I scroll Up again fast, I have to click the X button twice. Scrolling slowly seems to be fine.

**Comment by cirino** [comment]
To close with ESC, you have to click the item before.

**Comment by prabintim** [comment]
It's not an issue when used in a practical way.
