### ISSUE TITLE
Contact form on github pages

### ISSUE THREAD

**Issue by meeoh** [StartBootstrap/startbootstrap-agency#67]
Trying to get the contact form working, changed the email on line 19 of contact_me.php however im still getting 405 method not allowed (not hosting locally)

**Comment by davidtmiller** [comment]
GitHub Pages doesn't have a mail server so the form isn't going to work out of the box and will require some additional configuration.

Check out this article that offers some solutions http://sebastien.saunier.me/blog/2014/04/15/you-do-not-need-a-database-for-your-contact-form.html - Wufoo or Formspree are good alternatives to a mail server.
