### ISSUE TITLE
Menu dropdown on mobile safari not auto close

### ISSUE THREAD

**Issue by hfz** [StartBootstrap/startbootstrap-agency#68]
How to make Menu dropdown on mobile safari auto close after choosing? Thank you

**Comment by MisterSchmitz** [comment]
I haven't tested on Safari, but I was experiencing a similar issue on the mobile size in Desktop Chrome and Samsung's Android browsers. It was a simple fix for me.

In agency.js script, change the code from this: 
`$('.navbar-collapse ul li a:not(.dropdown-toggle)').click(function() {
        $('.navbar-toggle:visible').click();
    });`

to this:
`$('.navbar-collapse ul li a').click(function(){ 
            $('.navbar-toggle:visible').click();
    });`

**Comment by hfz** [comment]
Thank you!

**Comment by davidtmiller** [comment]
Fixed in #69. Thanks @MisterSchmitz!
