### ISSUE TITLE
How change the css code

### ISSUE THREAD

**Issue by ghost** [StartBootstrap/startbootstrap-agency#71]
Hi, 

I can't change the image and the color. 
How to do ?

thx

**Comment by davidtmiller** [comment]
You can either use the LESS files that come with the theme and recompile them into new CSS, or you can go through the CSS files and try to target each color manually and change them. Be aware the the theme by default loads the minified CSS called `agency.min.css` and if you're making changes to the `agency.css` file you need to load that one instead in the `<head>` tag of the page.

**Comment by bdyan** [comment]
Good day, I downloaded startbootstrap-agency-master. gulp task runs well without errors , however gulp.js does not display results on browser.

**Comment by Ancy-seles** [comment]
How can i change the background color in navbar-toggle ? Its white now and i would like to change it as black
