### ISSUE TITLE
Link not returning to original colour

### ISSUE THREAD

**Issue by ParsaAkbari** [StartBootstrap/startbootstrap-agency#77]
If you click on a link in the top nav bar e.g "Team" the text of the link will change colour but this will not return back to the original white colour even if you scroll back up the page.

**Comment by ionescu77** [comment]
Is it a similar behaviour to this: Issue #12 
If so, then there is a code snippet in the second comment, some javascript to release the focus of the button pressed.

I thought the fix was merged long ago. I will try to have a look this weekend.

**Comment by ParsaAkbari** [comment]
Yep same issue.

**Comment by ionescu77** [comment]
I post here the workaround, please let me know if it works as expected. I will try to push it later.

Workaround (see Issue #12 ):
- open js/agency.js
- add the following

``` javascript
$(".btn-xl").mouseup(function(){
    $(this).blur();
})

$(".page-scroll").mouseup(function(){
    $(this).blur();
})
```
- reload
