### ISSUE TITLE
Disabling nav mobile toggle for tablet media queries

### ISSUE THREAD

**Issue by brainhappy** [StartBootstrap/startbootstrap-agency#80]
Wonderful theme! 

I'm wondering how to untoggle the mobile navigation look (dropdown button) for tablet-sized devices (480px and up).  Unfortunately, the mobile nav clashes with my tablet design of a site i'm working on.

I've read through all the jquery and js files, but can't seem to find where I could change this.

Many thanks!

**Comment by davidtmiller** [comment]
You'll need to mess with the Bootstrap breakpoints on the navigation menu. It can be kind of a hassle but that's how to do it.
