### ISSUE TITLE
Contact Form not working with Github.io

### ISSUE THREAD

**Issue by khoitle** [StartBootstrap/startbootstrap-agency#87]
Any solutions to the form via gh-pages?

<img width="1226" alt="screen shot 2016-12-08 at 3 37 21 pm" src="https://cloud.githubusercontent.com/assets/20734065/21026801/3c7f1294-bd5c-11e6-954c-0e16c25d3f49.png">

**Comment by FireEmerald** [comment]
@KhoiLe89 startbootstrap-agency is using the default [`mail()`](https://github.com/BlackrockDigital/startbootstrap-agency/blob/master/mail/contact_me.php#L24)-function of [php](http://php.net/manual/de/function.mail.php).

> **Question:** Send email from static page hosted on GitHub Pages (?)
> **Answer:** This cannot be done natively on GitHub pages.

Take a look [here](http://stackoverflow.com/a/24348250) for further informations.

**Comment by davidtmiller** [comment]
@FireEmerald Thanks for the support here. Yes email cannot be sent from GitHub Pages hosted pages. You'll need to find some sort of workaround for this.
