### ISSUE TITLE
no error message when sending contact form

### ISSUE THREAD

**Issue by Godsgrav3** [StartBootstrap/startbootstrap-agency#99]
I don't get an error message when the return on the form is false. I tested this by commenting everything in contact_me.php and placing return false on line 1.

How can I fix this?

**Comment by FireEmerald** [comment]
Modify your `js/contact_me.js` and add after [L24](https://github.com/BlackrockDigital/startbootstrap-agency/blob/master/js/contact_me.js#L24):

```dataType: "json",```

**Comment by Godsgrav3** [comment]
Thank you FireEmerald!

**Comment by FireEmerald** [comment]
I deleted my earlier comment, because that wasn't a valid fix. If you replace the content of your **`contact_me.php`** with **`return false;`** - this won't trigger what would happen if the **`mail();`** function would fail.

**Comment by Godsgrav3** [comment]
Hi FireEmerald,

This works perfectly, I changed I minor thing because of the google captcha.

Thanks for your help!
